server:
  port: 9527
spring:
  application:
    name: spring-cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: zuul9527
    prefer-ip-address: true
info:
  app.name: wei-springcloud
  company.name: wei.com

zuul:
  routes:
    mydept.serverId: spring-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /wei